confirm-before-quit = false
working-dir = "C:\\Users\\me\\Coding"

[editor]
program = "nvim"
args = []

[window]
opacity = 0.9
blur = true
decorations = "enabled"
mode = "Maximized"

[renderer]
performance = "high"
backend = "automatic"

[keyboard]
use-kitty-keyboard-protocol = true
disable-ctlseqs-alt = true

[fonts]
family = "BerkeleyMono Nerd Font"
size = 14

[[fonts.extras]]
family = "Sarasa Mono SC Nerd"

[[fonts.extras]]
family = "MesloLGS NF"

[[fonts.extras]]
family = "SF Pro"

[[fonts.extras]]
family = "FOT-TsukuAOldMin Pr6N"

[colors]
background = '#24283b'
foreground = '#c0caf5'
selection-background = '#364a82'
selection-foreground = '#c0caf5'
cursor = '#c0caf5'
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'
light_black = '#414868'
light_red = '#f7768e'
light_green = '#9ece6a'
light_yellow = '#e0af68'
light_blue = '#7aa2f7'
light_magenta = '#bb9af7'
light_cyan = '#7dcfff'
light_white = '#c0caf5'

[[bindings.keys]]
key = "v"
with = "super"
action = "Paste"
[[bindings.keys]]
key = "c"
with = "super"
action = "Copy"
