#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh

yabai -m config layout bsp
yabai -m config mouse_follows_focus        off 
yabai -m config focus_follows_mouse        off 
yabai -m config window_placement           second_child
yabai -m config window_shadow              float
yabai -m config top_padding                20
yabai -m config bottom_padding             10
yabai -m config left_padding               10
yabai -m config right_padding              10
yabai -m config window_gap                 10
yabai -m config window_opacity             on
yabai -m config active_window_opacity      0.96
yabai -m config normal_window_opacity      0.95
yabai -m config external_bar               all:39:0
yabai -m config window_border              on 
yabai -m config window_animation_duration  0.15 
yabai -m config active_window_border_color 0xffe1e3e4
yabai -m config normal_window_border_color 0xff2a2f38
yabai -m config insert_feedback_color      0xff9dd274

sudo yabai --load-sa
